### PR TITLE
convert to array

### PR DESCRIPTION
**Pull request by lloricode**
CI loader view only array accepted in 2nd parameter,
im using CI-3.1.3

### CODE REVIEW

**Comment by scoumbourdis** [comment]
Thanks for that. A very clever and quick fix only for Codeigniter 3.1.3 . I will prepare an urgent fix for that

**Comment by lloricode** [comment]
even me confuse, then I just seen how grocery-crud pass parameter in ci view

**Comment by scoumbourdis** [comment]
Yes. This was already reported and solved at the forums: http://www.grocerycrud.com/forums/topic/3775-bug-with-ci-313/

**Comment by scoumbourdis** [comment]
And... also released in public :D This is though a silent release. Thank you for your pull request 👍

**Comment by lloricode** [comment]
hmm maybe CI need a update for accepting parameter by view. I try to find some more info of this situation. by the way thanks :)

**Pull request merged**
