### PR TITLE
Adding new features for disable search in list table and disable sort table in specific fields

### PR DESCRIPTION
**Pull request by willmendesneto**
Adding new features for disable search in list table and disable sort table in specific fields

### CODE REVIEW

**Comment by tarekshaker** [comment]
Is there anyway to do the same with datatables theme !?

**Comment by portapipe** [comment]
@tarekshaker you can use javascript (or jQuery) to hide it. Right click on the field you want to hide and use the class (or the ID better) to hide it (even via CSS!).

**Comment by tarekshaker** [comment]
@portapipe It's a good temporary solution, hope it can be solved from grocery core functions soon

**Comment by portapipe** [comment]
@tarekshaker sure is a temporary solution, but this feature is not even added on the other themes, so actually is the ONLY solution :)
We'll see how to implement this in the future versions :)

**Comment by willmendesneto** [comment]
Closing this pull request because of the lack in the replies. Thanks folks

**Comment by scoumbourdis** [comment]
Did create two new tickets for that: https://github.com/scoumbourdis/grocery-crud/issues/444 and https://github.com/scoumbourdis/grocery-crud/issues/445

I will follow the approach of @willmendesneto but in a way to be available for all the themes. I will inform this pull request once this is done as well

Regards
Johnny

**Pull request closed without merging**
